spring:
  application:
    name: waka-wiki-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVICE_HOST:nacos}:${NACOS_SERVICE_PORT:8848}

server:
  port: 8000

management:
  server:
    port: 7001
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: error
    org.springframework: warn
  file:
    name: waka.waki.gateway.log
    path: /var/log/waka.waki/gateway
