spring:
  application:
    name: waka-wiki-gateway
  cloud:
    nacos:
      server-addr: ${NACOS_SERVICE_HOST:nacos}:${NACOS_SERVICE_PORT:8848}
    gateway:
      routes:
        - id: route_auth_server
          uri: lb://${AUTH_SERVICE:waka-waki-auth-server}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

server:
  port: 8000

management:
  server:
    port: 7001
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: error
    org.springframework: warn
  file:
    name: application.log
    path: /var/logs/waka-waki-gateway
