version: "3"

networks: 
  outer-link:

services: 

  ### 数据库
  # docker run -it --network waka-waki_outer-link --rm mysql mysql -hmysql -uwaka-waki -p
  mysql: 
    image: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file: 
      - .env
      - ./config/mysql/.env
    volumes: 
      # sql初始化
      - ./config/mysql/initdb.d/:/docker-entrypoint-initdb.d/
      # - ./data/mysql/:/var/lib/mysql/
    expose: 
      - 3306
    networks:
      - default
      - outer-link 
    restart: always

  ### 缓存
  # docker run -it --network waka-waki_outer-link --rm redis redis-cli -h redis -a ${password}
  redis:
    image: redis
    command: --requirepass "${REDIS_SERVICE_PASSWORD}"
    expose:
      - 6379
    networks:
      - default
      - outer-link
    restart: always

  ### nginx 充当 dns + cdn
  dns.cdn:
    image: nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./deployment/waka-waki-pages/:/usr/share/nginx/html/
    ports:
      - "80:80"

  ### nacos 注册中心

  nacos1:
    hostname: nacos1
    image: nacos/nacos-server
    env_file: 
      - .env
      - ./config/nacos/.env
    volumes:
      # - ./data/nacos/nacos1/logs/:/home/nacos/logs/
      - ./config/nacos/nacos.custom.properties:/home/nacos/init.d/custom.properties
    expose:
      - 8848
    networks:
      default:
        aliases:
          # load balance for docker dns in default network, nacos for domain name
          - "nacos"
    depends_on:
      - mysql
    restart: always

  nacos2:
    hostname: nacos2
    image: nacos/nacos-server
    env_file: 
      - .env
      - ./config/nacos/.env
    volumes:
      # - ./data/nacos/nacos2/logs/:/home/nacos/logs/
      - ./config/nacos/nacos.custom.properties:/home/nacos/init.d/custom.properties
    expose:
      - "8848"
    networks:
      default:
        aliases:
          # load balance for docker dns in default network, nacos for domain name
          - "nacos"
    depends_on:
      - mysql
    restart: always
